name = "txtumblr"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
workers_dev = true

routes = [
	{ pattern = "txtumblr.com", custom_domain = true },
	{ pattern = "www.txtumblr.com", custom_domain = true },
	{ pattern = "fxtumblr.stellers.gay", custom_domain = true },
	{ pattern = "txtumblr.stellers.gay", custom_domain = true },
	{ pattern = "fxtumblr.suckerberg.gay", custom_domain = true },
	{ pattern = "txtumblr.suckerberg.gay", custom_domain = true }
]

kv_namespaces = [
	{ binding = "AUTH", id = "7f7518856e254c85af804c96c127f13b"}
]

[vars]
TUMBLR_CONSUMER_KEY = "GmsefnPqQxQ8WawhwtYUx7cWUPW9SZFMppM9qKCha1VrLaJ2kp"
